import { Document, Types } from "mongoose";

// ENHANCED: Added OTP verification, phone number, and presence tracking
export interface UserProps extends Document {
  email: string;
  password: string;
  name?: string;
  avatar?: string;

  
  // Online presence tracking
  isOnline?: boolean; // NEW: Real-time online status
  lastSeen?: Date; // NEW: Changed from string to Date for MongoDB
  
  // OTP verification fields
  verifyOTP?: string; // NEW: Stores the OTP code (hashed)
  verifyOTPExpiredAt?: number; // NEW: Timestamp when OTP expires
  isVerified?: boolean; // NEW: Has user verified their email/phone
  
  // Push notification tokens
  pushTokens?: string[]; // NEW: Array of Expo push tokens for notifications
  
  createdAt?: Date; // NEW: Auto-generated by Mongoose timestamps
  updatedAt?: Date; // NEW: Auto-generated by Mongoose timestamps
}

// ENHANCED: Added unread tracking and typing indicators
export interface ConversationProps extends Document {
  _id: Types.ObjectId;
  type: "direct" | "group";
  name?: string; // Required for group chats
  participants: Types.ObjectId[]; // References to User._id
  lastMessage?: Types.ObjectId; // NEW: Reference to Message._id
  createdBy?: Types.ObjectId; // NEW: Reference to User._id who created the conversation
  avatar?: string; // Group avatar URL
  
  // Unread message tracking per participant
  unreadCount?: Map<string, number>; // NEW: { userId: unreadCount }
  lastReadAt?: Map<string, Date>; // NEW: { userId: lastReadTimestamp }
  
  // Typing indicator state (not persisted, handled via Socket.IO)
  // But you may want to store who's currently typing for reconnection scenarios
  typingUsers?: Types.ObjectId[]; // NEW: Array of user IDs currently typing
  
  createdAt: Date;
  updatedAt: Date;
}

// NEW: Message schema with read receipts and delivery status
export interface MessageProps extends Document {
  _id: Types.ObjectId;
  conversationId: Types.ObjectId; // Reference to Conversation._id
  senderId: Types.ObjectId; // Reference to User._id
  content: string; // Text content
  type: "text" | "image" | "file" | "audio" | "video"; // NEW: Added more media types
  
  // Attachments
  attachment?: string; // URL to uploaded file (S3, Cloudinary, etc.)
  attachmentMetadata?: {
    fileName?: string;
    fileSize?: number; // In bytes
    mimeType?: string;
  };
  
  // Delivery and read tracking
  deliveredTo?: Types.ObjectId[]; // NEW: Array of user IDs who received the message
  deliveredAt?: Date; // NEW: When message was delivered to server
  
  readBy?: Types.ObjectId[]; // NEW: Array of user IDs who read the message [web:18]
  readAt?: Map<string, Date>; // NEW: { userId: readTimestamp } for detailed tracking
  
  // Message status flags
  isEdited?: boolean; // NEW: Was this message edited
  editedAt?: Date; // NEW: When was it last edited
  isDeleted?: boolean; // NEW: Soft delete flag
  deletedAt?: Date; // NEW: When was it deleted
  deletedFor?: Types.ObjectId[]; // NEW: User IDs who deleted this message (for "Delete for me")
  
  // Reply/Thread support
  replyTo?: Types.ObjectId; // NEW: Reference to another Message._id
  
  createdAt: Date;
  updatedAt: Date;
}

// NEW: OTP Verification Schema (temporary storage)
export interface OTPProps extends Document {
  email: string;
  otp: string;
  expiresAt: Date;
  attempts?: number;
  isUsed?: boolean;
  createdAt: Date;
}

// NEW: Typing Indicator (Optional - usually handled via Socket.IO only)
// Only create this if you want to persist typing state for reconnections
export interface TypingIndicatorProps extends Document {
  conversationId: Types.ObjectId;
  userId: Types.ObjectId;
  isTyping: boolean;
  lastTypingAt: Date; 
  createdAt: Date;
  updatedAt: Date;
}

// NEW: Notification Schema (for push notifications)
export interface NotificationProps extends Document {
  userId: Types.ObjectId; // Recipient
  type: "message" | "mention" | "reaction" | "group_invite"; // Notification types
  conversationId?: Types.ObjectId; // Related conversation
  messageId?: Types.ObjectId; // Related message
  senderId?: Types.ObjectId; // Who triggered the notification
  
  // Notification content
  title: string;
  body: string;
  data?: Record<string, any>;
  
  // Status
  isRead: boolean;
  readAt?: Date;
  isSent: boolean; 
  sentAt?: Date;
  
  createdAt: Date;
  updatedAt: Date;
}

// NEW: Read Receipt Schema (Alternative approach - separate collection) [web:18]
// Use this if you want to track read receipts separately for better scalability
export interface ReadReceiptProps extends Document {
  messageId: Types.ObjectId; // Reference to Message._id
  conversationId: Types.ObjectId; // Reference to Conversation._id
  userId: Types.ObjectId; // Who read the message
  readAt: Date; // When they read it
  createdAt: Date;
}

// NEW: User Presence Schema (Optional - for tracking online/offline history)
export interface UserPresenceProps extends Document {
  userId: Types.ObjectId;
  status: "online" | "offline" | "away"; // User status
  lastSeen: Date;
  socketId?: string; // Current Socket.IO connection ID
  deviceInfo?: {
    platform: "ios" | "android" | "web";
    deviceId: string;
  };
  createdAt: Date;
  updatedAt: Date;
}
